### ISSUE TITLE
Kleuren contrast

### ISSUE THREAD

**Issue by driezie** [Naddybs/look-and-feel-living-styleguide#1]
Website ziet er prima uit alleen zijn er sommige headers die ik slecht kan zien omdat de kleur wit is en de achtergrond is light grijs achtig. Probeer hier een goeie contrast te adden.

**Comment by saschavanvliet** [comment]
Ik heb de kleur van bijvoorbeeld het kopje 'icons' veranderd om een beter contrast te krijgen. Zo is het beter zichtbaar voor de gebruiker.
