### ISSUE TITLE
Zorg dat er niet meer dan 10 a 12 woorden op een regel staan

### ISSUE THREAD

**Issue by SamaraFellaDina** [Naddybs/look-and-feel-living-styleguide#3]
Zorg dat een zin niet meer dan 10 a 12 woorden heeft per regel

`max-width: 30 em;`

Je kan ook per regel instellen dat er 45 a 75 character per regel wordt.

**Comment by saschavanvliett** [comment]
Dit is nu door mij aangepast door een max width van 30 em toe te voegen!
